name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: VS Build Type
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Set Build Type
        id: build_type
        run: echo "::set-output name=build_type::${{ github.event.inputs.build_type || 'Release' }}"

      - name: Publish .NET Core Project
        run: dotnet publish HomeRecipes.SPA/HomeRecipes.SPA.csproj -c ${{ steps.build_type.outputs.build_type }} -o ${{ steps.build_type.outputs.build_type }} --nologo

      - name: Rename appsettings
        run: |
          if [ "${{ steps.build_type.outputs.build_type }}" = "Release" ]; then
            mv ${{ steps.build_type.outputs.build_type }}/wwwroot/appsettings.Release.json ${{ steps.build_type.outputs.build_type }}/wwwroot/appsettings.json
          else
            mv ${{ steps.build_type.outputs.build_type }}/wwwroot/appsettings.Development.json ${{ steps.build_type.outputs.build_type }}/wwwroot/appsettings.json
          fi

      - name: Copy index.html to 404.html
        run: cp ${{ steps.build_type.outputs.build_type }}/wwwroot/index.html ${{ steps.build_type.outputs.build_type }}/wwwroot/404.html

      - name: Add .nojekyll file
        run: touch ${{ steps.build_type.outputs.build_type }}/wwwroot/.nojekyll

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ steps.build_type.outputs.build_type }}/wwwroot
